apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-openshift-testing
spec:
  vendor: eduk8s.io
  title: Testing of OpenShift
  description: A sample workshop using the OpenShift web console
  url: https://github.com/eduk8s/lab-openshift-testing
  content:
    files: github.com/eduk8s-tests/lab-openshift-testing
  session:
    namespaces:
      budget: default
    applications:
      console:
        enabled: true
        vendor: openshift
        openshift:
          version: "4.3"
